# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: selfhosted02
#pool:
#  vmImage: 'ubuntu-latest'

steps:

- bash: echo "hello world"

- task: SSH@0
  inputs:
    sshEndpoint: 'win-target'
    runOptions: 'commands'
    commands: 'hostname'
    readyTimeout: '20000'

#- script: |
#    echo Downloaded $(env.secureFilePath)
#    mv $(env.secureFilePath) $(System.DefaultWorkingDirectory)